#! /bin/bash

# This script may ONLY be run on Linux!
OS=`uname`
if [ ${OS} != "Linux" ]; then
	printf "The '$0' script is ONLY executable on a 'Linux' machine!\n"
	exit 255
fi

ant -f build.xml -Dspecfile=tomcatjss.spec rpms
