name: Initialization
on:
  workflow_call:
    secrets:
      BASE64_OS:
        required: false
      BASE64_REPO:
        required: false
    outputs:
      base-image:
        value: ${{ jobs.init.outputs.base-image }}
      repo:
        value: ${{ jobs.init.outputs.repo }}
      registry:
        value: ${{ jobs.init.outputs.registry }}
      registry-namespace:
        value: ${{ jobs.init.outputs.registry-namespace }}

jobs:
  init:
    name: Initializing workflow
    runs-on: ubuntu-latest
    outputs:
      base-image: ${{ steps.init.outputs.base-image }}
      repo: ${{ steps.init.outputs.repo }}
      registry: ${{ steps.init.outputs.registry }}
      registry-namespace: ${{ steps.init.outputs.registry-namespace }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Initialize workflow
        id: init
        env:
          BASE64_OS: ${{ secrets.BASE64_OS }}
          BASE64_REPO: ${{ secrets.BASE64_REPO }}
          REGISTRY: ${{ vars.REGISTRY }}
          REGISTRY_NAMESPACE: ${{ vars.REGISTRY_NAMESPACE }}
        run: |
          tests/bin/init-workflow.sh
