name: Publish Tomcat JSS

on:
  push:
    branches:
      - master

jobs:
  init:
    name: Initialization
    uses: ./.github/workflows/init.yml
    secrets: inherit
    if: vars.REGISTRY != ''

  build:
    name: Waiting for build
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Building Tomcat JSS'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

  publish:
    name: Publishing Tomcat JSS
    needs: [init, build]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: vars.REGISTRY == 'ghcr.io'

      - name: Log in to other container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        if: vars.REGISTRY != 'ghcr.io'

      - name: Retrieve tomcatjss-dist image
        uses: actions/cache@v3
        with:
          key: tomcatjss-dist-${{ github.sha }}
          path: tomcatjss-dist.tar

      - name: Publish tomcatjss-dist image
        run: |
          docker load --input tomcatjss-dist.tar
          docker tag tomcatjss-dist ${{ needs.init.outputs.registry }}/${{ needs.init.outputs.registry-namespace }}/tomcatjss-dist:latest
          docker push ${{ needs.init.outputs.registry }}/${{ needs.init.outputs.registry-namespace }}/tomcatjss-dist:latest
